driver: "YOUR PATH\\chromedriver.exe"
naukri:
  url: 'https://www.naukri.com/'
  username: "username"
  password: "password"

job_preferences:
  location: 'Dubai'
  maximum_lpa: '15'
  minimum_lpa: '10'
  role: 'Data Engineer'
  skill_sets: ['Python', 'Airflow', 'Kubernetes', 'Ingestion']